[package]
name = "wordle-rs"
description = "Wordle game written in rust"
version = "0.1.0"
edition = "2021"
authors = ["Quang Le <iamquang95@gmail.com>"]

[dependencies]
anyhow = "1.0.53"
lazy_static = "1.4.0"
rand = "0.8.4"
termion = "1.5.6"